title: Flask Project Template
description: A starter Flask project with Jinja, SQLite and PicoCSS
author: DT Dept.

theme: null

navigation:
  - title: Task
    url: /instructions/
  - title: Evidence
    url: /evidence/
  - title: Guides
    url: /guides/

