title: Flask Project

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

# minima:
#   skin: dark

#   nav_pages:
#     - instructions/index.md
#     - evidence/index.md
#     - guides/index.md

#   show_title: false

